@extends('layouts.app')
@section('content')
<h1 class="mb-4">Create Order</h1>
<form method="POST" action="{{ route('orders.store') }}" id="order-form">@csrf
<div class="card shadow-sm mb-3"><div class="card-body"><h5>Customer</h5><div class="row g-3"><div class="col-md-6"><label class="form-label">Name</label><input name="customer[name]" class="form-control" required></div><div class="col-md-6"><label class="form-label">Email</label><input name="customer[email]" type="email" class="form-control" required></div></div></div></div>
<div class="card shadow-sm"><div class="card-body"><div class="d-flex justify-content-between"><h5>Products</h5><button type="button" class="btn btn-outline-secondary btn-sm" id="add-line">+ Add Product</button></div><div id="lines" class="mt-3"></div><button class="btn btn-primary mt-3">Create Order</button></div></div></form>
<template id="line-template"><div class="row g-2 align-items-end order-line mb-2"><div class="col-md-8"><label class="form-label">Product</label><select class="form-select product-select" required></select></div><div class="col-md-2"><label class="form-label">Qty</label><input class="form-control qty" type="number" min="1" value="1" required></div><div class="col-md-2"><button type="button" class="btn btn-outline-danger w-100 remove">Remove</button></div></div></template>
<script>const products=@json($products);const lines=document.getElementById('lines');function addLine(){const el=document.getElementById('line-template').content.cloneNode(true);const row=el.querySelector('.order-line');const select=el.querySelector('.product-select');select.innerHTML='<option value="">Select product</option>'+products.map(p=>`<option value="${p.id}">${p.name} — ₹${Number(p.price).toFixed(2)} (Stock: ${p.stock_on_hand})</option>`).join('');row.querySelector('.remove').onclick=()=>row.remove();lines.appendChild(el);syncNames();}function syncNames(){document.querySelectorAll('.order-line').forEach((row,i)=>{row.querySelector('.product-select').name=`items[${i}][product_id]`;row.querySelector('.qty').name=`items[${i}][quantity]`;});}document.getElementById('add-line').onclick=addLine;addLine();</script>
@endsection
